# Generated by Django 4.0 on 2022-01-01 08:29

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacker_news_id', models.BigIntegerField(blank=True, default=-1)),
                ('newsly_news_id', models.BigIntegerField(blank=True, default=-1)),
                ('local', models.BooleanField(blank=True, default=False)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=50)),
                ('by', models.CharField(blank=True, default='', max_length=300)),
                ('time', models.BigIntegerField(blank=True, default=-1)),
                ('dead', models.BooleanField(blank=True, default=False)),
                ('kids', models.JSONField(blank=True, default=item.models.default_array)),
                ('parts', models.JSONField(blank=True, default=item.models.default_array)),
                ('text', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('descendants', models.IntegerField(blank=True, default=-1)),
                ('score', models.IntegerField(blank=True, default=-1)),
                ('parent', models.BigIntegerField(blank=True, default=-1)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id', 'type', '-time', 'title', 'text'], name='table_indexes'),
        ),
    ]
